### ISSUE TITLE
Fatal error: Class 'LBN_Assets' not found

### ISSUE THREAD

**Issue by robinmetral** [justinwhall/wp-buildhook-deploy#7]
I installed the plugin by moving the unzipped `littlebot-netlify` to my `plugins` directory.

On activation from my WP admin panel, I'm getting the same error as in #1:

`
Fatal error: Uncaught Error: Class 'LBN_Assets' not found in /wp-content/plugins/littlebot-netlify/littlebot-netlify.php:144 Stack trace: #0 /wp-content/plugins/littlebot-netlify/littlebot-netlify.php(217): Littlebot_Netlify->includes() #1 /wp-includes/class-wp-hook.php(286): Littlebot_Netlify->init('') #2 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /wp-settings.php(450): do_action('init') #5 /wp-config.php(89): require_once('/home/toonstru/...') #6 /wp-load.php(37): require_once('/home/...') #7 /wp-admin/admin.php(31): require_once('/home/...') #8 /hom in /wp-content/plugins/littlebot-netlify/littlebot-netlify.php on line 144
`

I assume I misinstalled the plugin, but I can't figure out how.

Whatever I did wrong could probably be added to the instructions in README :slightly_smiling_face:

**Comment by justinwhall** [comment]
Hmm, do you know what version of PHP you are running?

**Comment by robinmetral** [comment]
Yep, version 7.2.12

**Comment by justinwhall** [comment]
OK, ya. PHP 7.2 is a stricter with args. I was able to reproduce. Just pushed version 0.9.1 that should fix this issue. Apologies on the delay here BTW. Please let me know if you have any other issues.

**Comment by justinwhall** [comment]
Actually, this appears to be different than the issue I was thinking of. Are you sure you have the plugin installed correctly?

**Comment by robinmetral** [comment]
@justinwhall thanks for looking into this! I'm abroad this week, but when I get back home I'll try to reinstall release 0.9.1 of the plugin. I'll let you know how it goes :slightly_smiling_face:
